### ISSUE TITLE
Maneuver grid not showing in pilot view

### ISSUE THREAD

**Issue by ajmath** [timrisi/AuroraSquadBuilder#37]
Maneuver grids are not being shown on the pilot view despite being enabled in settings

This was observed in the latest iOS release as of 4/4/2018 on an iPhone SE

**Comment by timrisi** [comment]
I need to remove the setting for this one.  When I reformatted the pilot view, I didn't have a good place to display the maneuver dial (and still haven't been able to come up with one).  If you (or anyone else) have a suggestion where I could put it, I'm open to re-adding it.  For now though, just need to remove the option.

**Comment by timrisi** [comment]
Setting option removed in 78e24894de3834f27acc0d4c3d115a0223923197
